import type { ModelId } from '@/lib/models/model-id';
import type { ModelFeatures } from './model-features';

export const generatedModelFeatures = {
  'amazon/nova-lite': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-12-03'),
    knowledgeCutoff: new Date('2024-10-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: true,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'amazon/nova-micro': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-12-03'),
    knowledgeCutoff: new Date('2024-10-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'amazon/nova-pro': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-12-03'),
    knowledgeCutoff: new Date('2024-10-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: true,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'anthropic/claude-3-haiku': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-03-13'),
    knowledgeCutoff: new Date('2023-08-31'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'anthropic/claude-3-opus': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-02-29'),
    knowledgeCutoff: new Date('2023-08-31'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'anthropic/claude-3.5-haiku': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-10-22'),
    knowledgeCutoff: new Date('2024-07-31'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'anthropic/claude-3.5-sonnet': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-10-22'),
    knowledgeCutoff: new Date('2024-04-30'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'anthropic/claude-3.7-sonnet': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-02-19'),
    knowledgeCutoff: new Date('2024-10-31'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'anthropic/claude-opus-4': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-05-22'),
    knowledgeCutoff: new Date('2025-03-31'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'anthropic/claude-opus-4.1': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-08-05'),
    knowledgeCutoff: new Date('2025-03-31'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'anthropic/claude-sonnet-4': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-05-22'),
    knowledgeCutoff: new Date('2025-03-31'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'deepseek/deepseek-r1': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-01-20'),
    knowledgeCutoff: new Date('2024-06-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'deepseek/deepseek-r1-distill-llama-70b': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-01-20'),
    knowledgeCutoff: new Date('2024-07-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'google/gemini-2.0-flash': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-12-11'),
    knowledgeCutoff: new Date('2024-06-01'),
    input: {
      image: true,
      text: true,
      pdf: true,
      audio: true,
      video: true,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'google/gemini-2.0-flash-lite': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-12-11'),
    knowledgeCutoff: new Date('2024-06-01'),
    input: {
      image: true,
      text: true,
      pdf: true,
      audio: true,
      video: true,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'google/gemini-2.5-flash': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-06-17'),
    knowledgeCutoff: new Date('2025-01-01'),
    input: {
      image: true,
      text: true,
      pdf: true,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'google/gemini-2.5-pro': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-06-17'),
    knowledgeCutoff: new Date('2025-01-01'),
    input: {
      image: true,
      text: true,
      pdf: true,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'meta/llama-3.3-70b': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-12-06'),
    knowledgeCutoff: new Date('2023-12-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'meta/llama-4-maverick': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2025-04-05'),
    knowledgeCutoff: new Date('2024-08-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'meta/llama-4-scout': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2025-04-05'),
    knowledgeCutoff: new Date('2024-08-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'mistral/codestral': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-05-29'),
    knowledgeCutoff: new Date('2024-10-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'mistral/magistral-medium': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-03-17'),
    knowledgeCutoff: new Date('2025-06-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'mistral/magistral-small': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-03-17'),
    knowledgeCutoff: new Date('2025-06-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'mistral/ministral-3b': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-10-01'),
    knowledgeCutoff: new Date('2024-10-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'mistral/ministral-8b': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-10-01'),
    knowledgeCutoff: new Date('2024-10-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'mistral/mistral-large': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-11-01'),
    knowledgeCutoff: new Date('2024-11-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'mistral/mistral-small': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-09-01'),
    knowledgeCutoff: new Date('2025-03-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'mistral/mixtral-8x22b-instruct': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-04-17'),
    knowledgeCutoff: new Date('2024-04-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'mistral/pixtral-12b': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-09-01'),
    knowledgeCutoff: new Date('2024-09-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'mistral/pixtral-large': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-11-01'),
    knowledgeCutoff: new Date('2024-11-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'moonshotai/kimi-k2': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2025-07-11'),
    knowledgeCutoff: new Date('2024-10-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'morph/morph-v3-fast': {
    reasoning: false,
    toolCall: false,
    releaseDate: new Date('2024-08-15'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'morph/morph-v3-large': {
    reasoning: false,
    toolCall: false,
    releaseDate: new Date('2024-08-15'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'openai/gpt-4-turbo': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2023-11-06'),
    knowledgeCutoff: new Date('2023-12-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'openai/gpt-4.1': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2025-04-14'),
    knowledgeCutoff: new Date('2024-04-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'openai/gpt-4.1-mini': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2025-04-14'),
    knowledgeCutoff: new Date('2024-04-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'openai/gpt-4.1-nano': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2025-04-14'),
    knowledgeCutoff: new Date('2024-04-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'openai/gpt-4o': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-05-13'),
    knowledgeCutoff: new Date('2023-10-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: true,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'openai/gpt-4o-mini': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-07-18'),
    knowledgeCutoff: new Date('2023-10-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: true,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'openai/gpt-5': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-08-07'),
    knowledgeCutoff: new Date('2024-10-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'openai/gpt-5-mini': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-08-07'),
    knowledgeCutoff: new Date('2024-10-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'openai/gpt-5-nano': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-08-07'),
    knowledgeCutoff: new Date('2024-10-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'openai/gpt-oss-120b': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-08-05'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'openai/gpt-oss-20b': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-08-05'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'openai/o1': {
    reasoning: true,
    toolCall: false,
    releaseDate: new Date('2024-09-12'),
    knowledgeCutoff: new Date('2023-10-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'openai/o3': {
    reasoning: true,
    toolCall: false,
    releaseDate: new Date('2025-01-31'),
    knowledgeCutoff: new Date('2024-04-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'openai/o3-mini': {
    reasoning: true,
    toolCall: false,
    releaseDate: new Date('2025-01-31'),
    knowledgeCutoff: new Date('2024-04-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'openai/o4-mini': {
    reasoning: true,
    toolCall: false,
    releaseDate: new Date('2025-01-31'),
    knowledgeCutoff: new Date('2024-04-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'vercel/v0-1.0-md': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-05-22'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'vercel/v0-1.5-md': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-06-09'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'xai/grok-2': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-08-20'),
    knowledgeCutoff: new Date('2024-08-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'xai/grok-2-vision': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2024-08-20'),
    knowledgeCutoff: new Date('2024-08-01'),
    input: {
      image: true,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'xai/grok-3': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2024-12-09'),
    knowledgeCutoff: new Date('2024-10-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'xai/grok-3-fast': {
    reasoning: false,
    toolCall: true,
    releaseDate: new Date('2025-02-17'),
    knowledgeCutoff: new Date('2024-11-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'xai/grok-3-mini': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2024-12-09'),
    knowledgeCutoff: new Date('2024-10-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'xai/grok-3-mini-fast': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-02-17'),
    knowledgeCutoff: new Date('2024-11-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
  'xai/grok-4': {
    reasoning: true,
    toolCall: true,
    releaseDate: new Date('2025-07-09'),
    knowledgeCutoff: new Date('2025-07-01'),
    input: {
      image: false,
      text: true,
      pdf: false,
      audio: false,
      video: false,
    },
    output: {
      image: false,
      text: true,
      audio: false,
    },
  },
} satisfies Partial<Record<ModelId, ModelFeatures>>;
